services:
  app:
    build: .
    container_name: know_hub
    ports:
      - "8001:8000"
      - "8502:8501"
    environment:
      MILVUS_HOST: milvus
      MILVUS_PORT: 19530
    volumes:
      - ./uploads:/app/uploads
    restart: always
    depends_on:
      - milvus

  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    ports:
      - "19531:19530"
    restart: always
