version: "3.9"

services:
  app:
    build: .
    container_name: mini_rag_app
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    environment:
      MILVUS_HOST: host.docker.internal
      MILVUS_PORT: 19530
    volumes:
      - ./uploads:/app/uploads
    restart: always
